### ISSUE TITLE
How to use for Monero?

### ISSUE THREAD

**Issue by lacivert** [cnrig/cnrig#2]
I only see a tag for Monero but there is no info about that in Readme file. Is it available for monero mining? If yes, how?

**Comment by mode0x13** [comment]
The variant is auto-detected. It is sufficient to specify the algorithm, e.g. `-a cryptonight`.

I added examples configurations to the repo:
https://github.com/cnrig/cnrig/tree/master/examples

Monero:
`./cnrig -a cryptonight -o POOL_ADDRESS:PORT -u YOUR_MONERO_ADDRESS -p x`

Sumokoin:
`./cnrig -a cryptonight-heavy -o POOL_ADDRESS:PORT -u YOUR_SUMOKOIN_ADDRESS -p x`

Aeon:
`./cnrig -a cryptonight-light -o POOL_ADDRESS:PORT -u YOUR_AEON_ADDRESS -p x`
